### ISSUE TITLE
About supplementary material

### ISSUE THREAD

**Issue by SIQI9747** [Zhanxin-Gao/CPrompt#1]
Dear authors,
Really nice work! Would you please release the Supplementary Material for this paper?

More details  of the analysis would be very helpful. And I am curious that is there any experiment or analysis 1. to verify the prompt length of 50; 2. directly add prompt instead of prefix tuning; 3.add prompt at the 1st and 6th layers are the best choices?

**Comment by Zhanxin-Gao** [comment]
Hi SIQI9747, thank you for your comment!
We have now uploaded the supplementary material. 
We have not conducted the analysis about prompt setting 1 and 2. For 3, we found that inserting the prompt segment at the first and middle (6th) layers yields better results than placing it only at the first layer. But we are not sure that it’s the best choice.
