### ISSUE TITLE
About reproducing other methods

### ISSUE THREAD

**Issue by SIQI9747** [Zhanxin-Gao/CPrompt#3]
Dear author, 

Thank you for the supplementary materials. 

Regarding reproducing, I have a question about epochs. Take Cifar-100 as an example. Are you using the same epoch numbers as CPrompt (18 epochs) when producing all other methods (L2P, DualPrompt, CODAprompt)? Or following each method's original setting as their code provided (such as L2P & DualPrompt 5 epochs, DualPrompt 20 epochs)?

**Comment by Zhanxin-Gao** [comment]
Hi,
We execute the source code of previous SOTA methods and reproduce their methods on our backbone with the same experimental settings, presenting their best result.
