### ISSUE TITLE
About reproducing other mothods

### ISSUE THREAD

**Issue by 4vicii** [Zhanxin-Gao/CPrompt#4]
hi, how do you reproduce T10 Stanford Cars dataset on ESN?
I used the source codes of ESN but the results didn' t converge, like this:

cars
Accuracy curve:
[87.09, 35.75, 21.52, 10.39, 7.56, 4.58, 3.39, 2.98, 2.5, 2.01]
FAA: 2.01
FF: 7.8405555555555555

Can you give me the training hype params or config file?
thx

**Comment by Zhanxin-Gao** [comment]
Hi, you can try setting the batch size to 128.

**Comment by 4vicii** [comment]
Thx dude 🥹.I ll try it Sent from my iPhoneOn Aug 15, 2024, at 20:39, Zhanxin-Gao ***@***.***> wrote:﻿
Hi, you can try setting the batch size to 128.

**Comment by 4vicii** [comment]
> Hi, you can try setting the batch size to 128.

it does not work....

[[64.388 19.779  9.889  7.371  4.853]
 [ 0.     0.482  0.37   0.246  0.246]
 [ 0.     0.     0.134  0.178  0.178]
 [ 0.     0.     0.     0.206  0.125]
 [ 0.     0.     0.     0.     0.265]]
Accuracy curve:
[64.39, 10.68, 3.57, 2.04, 1.14]
FAA: 1.14
FF: 14.963000000000001

have a nice day dude

**Comment by 4vicii** [comment]
> Hi, you can try setting the batch size to 128.

it does not work....

[[64.388 19.779  9.889  7.371  4.853]
 [ 0.     0.482  0.37   0.246  0.246]
 [ 0.     0.     0.134  0.178  0.178]
 [ 0.     0.     0.     0.206  0.125]
 [ 0.     0.     0.     0.     0.265]]
Accuracy curve:
[64.39, 10.68, 3.57, 2.04, 1.14]
FAA: 1.14
FF: 14.963000000000001

have a nice day dude

**Comment by Zhanxin-Gao** [comment]
emmmm, what is the number of epochs when you train cars dataset. Maybe you could try increasing it to 130.

**Comment by 4vicii** [comment]
I’m really appreciate it and thank you dude 🥹Have a nice weekend 🫡 respect again 🫡On Aug 16, 2024, at 08:48, Zhanxin-Gao ***@***.***> wrote:﻿
emmmm, what is the number of epochs when you train cars dataset. Maybe you could try increasing it to 130.

**Comment by Zhanxin-Gao** [comment]
No problem at all! Thanks for the kind words 🙌  Does it work now
